name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build --tag ${{ secrets.DOCKER_USERNAME }}/flask_app:test .

    - name: Run Docker Compose
      run: |
        docker-compose up -d --build

    - name: Wait for the container to be healthy
      run: |
        sleep 30
        docker-compose ps

    - name: Run tests
      run: |
        docker-compose exec flask_app pytest

    - name: Build and push Docker image
      if: success()
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/flask_app:latest
        context: .
