name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      flask_app:
        build:
          context: .
        ports:
          - 5000:5000
        options: --runtime=nvidia

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: ${{ secrets.DOCKER_USERNAME }}/the_flask_app:test
        build-args:
          - BUILDKIT_INLINE_CACHE=1
        platforms: linux/amd64

    - name: Run Docker container
      run: docker-compose up -d

    - name: Run tests
      run: |
        docker-compose exec flask_app pytest

    - name: Build and push Docker image
      if: success()
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/the_flask_app:latest
        build-args:
          - BUILDKIT_INLINE_CACHE=1
        platforms: linux/amd64
